- local/templates/.default/components/bitrix/catalog.section/bestsellers/style.css
> edit style in  series

- local/templates/.default/components/bitrix/sale.order.ajax/order/props_format.php
> hidding rlab block

- css/style.css
- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog.section/this_book_reviews/result_modifier.php
- local/templates/.default/components/bitrix/catalog.section/this_book_reviews/style.css
- local/templates/.default/components/bitrix/catalog.section/this_book_reviews/template.php
Добавление и отображение поля "Должность" у эксперта - автора отзыва к книге, удаление маркеров у списка отзывов, реиндент кода шаблона.
> Fixing book reviews on book detail page (adding expert position field and removing markers on reviews list)

- local/templates/.default/components/bitrix/sale.basket.basket/basket/script.js
- local/templates/.default/components/bitrix/sale.order.ajax/order/props_format.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/summary.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
Отлаживал  функционал кастомизированных купонов, параллельно изменял код под наш code style/
> SUP-4311: Debug custom certificate

- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/style.css
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
добавление скрипта на проверку ios устройства
> SUP-4193: script for ios

- css/style.css
В карточке товара была проблема с версткой блока с авторами при включенном автокешировании, исправил ее.
> SUP-4306: Fixing style bug in catalog card

- local/modules/webgk.coupons/admin/.config.php
- local/modules/webgk.coupons/admin/coupon-list.php
- local/modules/webgk.coupons/admin/lang/coupon-list.php
Добавил в список купонов номер заказа в котором был куплен купон и номер заказа в котором он был использован, переделал фильтр.
> SUP-4291: Add functional in coupon list

- js/main.js
- local/php_interface/init.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/include/functions.php
- local/templates/.default/components/bitrix/search.page/search_common_page/result_modifier.php
- local/templates/.default/components/bitrix/search.page/search_common_page/style.css
- local/templates/.default/components/bitrix/search.page/search_common_page/template.php
Доработка верстки шаблона результатов поиска (для книг - добавление поля имени автора книги), доработка кодстайла.
> SUP-4489: adding author name's note on the search results, fixing codestyle

- ajax/customCoupon.php
- local/templates/.default/components/bitrix/sale.basket.basket/basket/script.js
Добавил проверку на активность купона по дате активности купона.
> SUP-4615: Add checking the activity of the coupon by date

- css/style.css
- local/templates/alpina_index/footer.php
Добавлена надпись о разработке в WebGK в футер
> Добавлена надпись о разработке в WebGK в футер

- local/php_interface/init.php
- personal/order/make/index.php
Стоимость доставки flippost теперь учитывается при оплате
> SUP-4788: Добавление стоимости Flippost

- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog/catalog_template/element.php
добавил обработку адресов, в которых встречается /temporary/ в карточке товара, в файле element.php
> SUP-4837: создание правила переадресации для некорректных адресов

- local/php_interface/init.php
- local/templates/.default/components/bitrix/search.page/search_common_page/result_modifier.php
- local/templates/.default/components/bitrix/search.page/search_common_page/template.php
- search/index.php
Разработка функционала по получению книг в результатах поиска из  введенного в поисковой строке имени автора-эксперта данного отзыва.
> SUP-4854: получение книг в поиске из привязанных отзывов экспертов

- local/templates/.default/components/bitrix/search.page/search_common_page/result_modifier.php
Если к книге прикреплено несколько авторов, то выводится теперь только первый
> SUP-5002: Фикс для вывода нескольких авторов

- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
изменение протокола сслылки брендов
> SUP-5009: изменение протокола сслылки брендов

- local/templates/.default/components/bitrix/search.page/search_common_page/result_modifier.php
- local/templates/.default/components/bitrix/search.page/search_common_page/template.php
Изменен источник данных для поля автор в поиске
> SUP-5002: Изменен источник данных для поля автор в поиске

- css/style.css
- gift/index.php
- local/php_interface/init.php
- local/templates/.default/components/bitrix/sale.personal.order.list/.default/lang/ru/template.php
- local/templates/.default/components/bitrix/sale.personal.order.list/.default/template.php
добавление в историю заказов трек номера
> SUP-5001: добавление в историю заказов трек номера

- local/templates/.default/components/bitrix/sale.personal.order.list/.default/template.php
добавление echo при выводе getmessage
> SUP-5001: добавление echo при выводе getmessage

- local/php_interface/init.php
- local/templates/.default/components/bitrix/sale.personal.order.list/.default/lang/ru/template.php
- local/templates/.default/components/bitrix/sale.personal.order.list/.default/style.css
- local/templates/.default/components/bitrix/sale.personal.order.list/.default/template.php
> SUP-5001: доработки по трек номеру

- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
Скрытие кнопки выбора пункта доставки PickPoint в случае, если выбрана другая служба доставки.
> SUP-5024: скрытие кнопки выбора пункта доставки PickPoint

- local/templates/.default/components/bitrix/sale.personal.order.list/.default/template.php
исправление ошибки на странице истории заказов
> SUP-5001: исправление ошибки на странице истории заказов

- onix/index.php
Создание скрипта по генерации файла ONIX-формата.
> SUP-4912: ONIX file generation

- onix/index.php
доработка скрипта генерации ONIX
> SUP-4912: доработка скрипта генерации ONIX

- local/templates/.default/components/bitrix/sale.order.ajax/order/confirm.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/lang/ru/template.php
- personal/order/payment/index.php
> SUP-5151: доработка формы счета-оферты

- local/templates/.default/components/bitrix/sale.order.ajax/order/confirm.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/lang/ru/template.php
- personal/order/payment/index.php
добавление слова "год" в заголовок формы счета-оферты
> SUP-5151: добавление слова "год" в заголовок формы счета-оферты

- local/templates/.default/components/bitrix/sale.order.ajax/order/confirm.php
- personal/order/payment/index.php
доработка формы счета-оферты (удаление полей телефона в графах "Покупатель" и "Грузополучатель")
> SUP-5410: доработка формы счета-оферты

- local/php_interface/init.php
доработка функции с учетом возможности деактивации свойства "Показывать иконку скидки", если активность скидки снята
> SUP-5453: доработка функции по событиям OnDiscountUpdate и OnDiscountAdd

- local/templates/.default/components/bitrix/sale.order.ajax/order/confirm.php
- personal/order/payment/index.php
редактирование множителя НДС для формы счета-оферты
> SUP-5456: редактирование множителя НДС для формы счета-оферты

- local/php_interface/init.php
доработка функции по активации свойства "показывать иконку скидки" (учтена возможность редактирования скидки, не заходя в саму скидку)
> SUP-5453: доработка функции по активации свойства "показывать иконку скидки"

- desktop_app/headers.php
- desktop_app/index.php
- desktop_app/router.php
- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog.section/bestsellers/template.php
- local/templates/.default/components/bitrix/catalog.section/coming-soon/template.php
- local/templates/.default/components/bitrix/catalog.section/new_books_section/template.php
доработка AJAX-подгрузки новых товаров раздела с учетом сортировки
> SUP-5482: доработка AJAX-подгрузки новых товаров раздела с учетом сортировки

- local/templates/.default/components/bitrix/catalog.section/ajax_section_page/template.php
доработка условий для отображения иконки скидки на странице раздела (если отмечено свойство "Показать иконку скидки")
> SUP-5453: доработка условий для отображения иконки скидки на странице раздела

- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog.section/bestsellers/template.php
- local/templates/alpina_index/footer.php
доработка ссылки на WebGK в футере
> Без задачи: доработка ссылки на WebGK в футере

- js/inputmask.date.extension.js
- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
- local/templates/alpina_basket/header.php
> SUP-5623: правка скрипта маски по дате

- local/templates/.default/components/bitrix/main.profile/user_profile_sailplay/script.js
> SUP-5676: правка ошибки скрипта

- js/main.js
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/lang/ru/template.php
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
Исправлено некорректное обновление блока с информацией до следующей скидки
> SUP-5710: Исправление блока с ценой в карточке товара 

- flippost/delivery_post.php
- flippost/flippost.js
- local/templates/.default/components/bitrix/sale.order.ajax/order/delivery.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/lang/ru/template.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/style.css
в шаблоне оформления заказа добавлен вывод сроков доставки для flippost. Данные берутся из API
> SUP-5727: добавление сроков доставки для flippost

- local/templates/.default/components/bitrix/catalog.section/bestsellers/template.php
редактирование условий отображения иконки скидки на странице бестселлеров
> SUP-5754: редактирование условий отображения иконки скидки

- local/admin/guru_export.php
- local/admin/lang/ru/guru_export.php
- local/php_interface/init.php
- test.php
создание административной страницы для экспорта заказа в доставка гуру
руками перенести файл
/bitrix/admin/guru_export.php
> SUP-5506: add admin page for orders export to DG

- local/templates/.default/components/bitrix/catalog.section/new_books_section/template.php
доработка условий отображения значка скидки на странице новинок
> SUP-5754: доработка условий отображения значка скидки

- js/main.js
- local/templates/.default/components/bitrix/catalog.section/ajax_section_page/template.php
- local/templates/.default/components/bitrix/catalog/catalog_template/section.php
доработка назначения кнопки переключения сортировки по популярности на странице раздела
> SUP-5800: доработка назначения кнопки переключения сортировки

- local/templates/.default/components/bitrix/sale.order.ajax/order/include/guru/js/guru.js
1) Для доставки гуру удален срок доставки из попапа
2) Для клиентов к сроку доставки докидывается 2 дня
3) Удален левый дебаг код из js файла
> SUP-5506: Правки по дате доставки

- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/result_modifier.php
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
- test2.php
доработка вывода цен в карточке товара (учитывая условия в правилах работы с корзиной)
> SUP-5864: доработка вывода цен в карточке товара

- tools/loadToXls.php
- tools/updateCertificate.php
исправление условия при обновлении сертификатов
> SUP-5933: исправление условия при обновлении сертификатов

- local/php_interface/init.php
удаление кода, отвечающего за подмену логина на строку, содержащую "newuser_"
> SUP-5779: удаление кода, отвечающего за подмену логина

- local/templates/.default/components/bitrix/news/events/news.php
корректировка фильтра для блока ближайших мероприятий
> SUP-6107: корректировка фильтра для блока ближайших мероприятий

- local/templates/.default/components/bitrix/catalog.section/ajax_section_page/template.php
- local/templates/.default/components/bitrix/catalog/catalog_template/section.php
корректировка сортировки страницы раздела каталога (сортировка по свойству SOON_DATE_TIME) и тестирование функционала
> SUP-6294: корректировка сортировки страницы раздела каталога и тестирование функционала

- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
скрытие полей из формы оформления заказа
> SUP-6335: скрытие полей из формы оформления заказа

- boxbery/boxbery.js
- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
правка выбора города и региона
> SUP-6291: правка выбора города и региона

- js/main.js
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/script.js
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/style.css
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
> Спиннер во время ajax загрузки

- local/php_interface/init.php
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
> Небольшие правки

- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
> epages задолбали этим сообщением!

- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/component_epilog.php
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
Добавлены метаданные для твиттера
Убрано сообщение о скидке, если в корзине пусто и нет накопительной суммы
Можно заливать
> Метаданные, сообщение о сумме до скидки

- css/style.css
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
- local/templates/alpina_index/header.php
> New latest seen, styles update, opensearch

- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
удаление кода скрытия полей формы оформления заказа после смены местоположения
> SUP-6501: удаление кода скрытия полей формы оформления заказа после смены местоположения

- local/php_interface/init.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/delivery.php
добавление службы доставки для курьера по москве
> SUP-6591: добавление службы доставки для курьера по москве

- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
> SUP-7050: правка стилей

- order_update/pre_order.php
функция обновления цены товара предзаказа
> SUP-7153: функция обновления цены товара предзаказа

- local/php_interface/init.php
Создание функции на обновление статуса заказа при смене статуса товара
> SUP-7224: adding handler UpdateStatusOrderOnProduct

- local/templates/.default/components/bitrix/news.list/archive_events_full_list/style.css
> SUP-7628: доработка стилей для футера на странице мероприятий

- css/style.css
> SUP-7726 Пункт 20 ТЗ #7726

- css/style.css
- local/templates/.default/components/bitrix/catalog.section/new_books_section/template.php
> SUP-7726 Пункты ТЗ  #7726 21,22,24

- custom-scripts/index.php
- custom-scripts/test2.php
Добавлена ссылка на скрипт "test2.php" на индексной странице в разделе "custom-scripts"
> SUP-7868: add custom script to "custom-scripts" folder

- local/php_interface/init.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/delivery.php
SUP-7926: добавление проверки на время
>  SUP-7926: добавление проверки на время

- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
SUP-7926: установка условия доставки в карточке товара
>  SUP-7926: установка условия доставки в карточке товара

- local/templates/.default/components/bitrix/sale.order.ajax/order/paysystem.php
SUP-7717: пункт 9 по свойству "под заказ"
>  SUP-7717: пункт 9 по свойству "под заказ"

- custom-scripts/checkdelivery/options.php
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/result_modifier.php
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/delivery.php
- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
создание обработчиков для управления датами доставки
>  SUP-7942: создание обработчиков для управления датами доставки

- local/php_interface/init.php
SUP-7948: EventProductQuantity()
> SUP-7948: EventProductQuantity()

- local/templates/.default/components/bitrix/catalog.section/slider_on_main_bestsellers/template.php
Изменена ссылка для слайдера "Бестселлеры"
> Sup #7726 changed link for bestcellers_slider

- local/php_interface/init.php
SUP-7989: addind status update
> SUP-7989: addind status update

- local/templates/.default/components/bitrix/sale.order.ajax/order/template.php
SUP-7657: правки индекса в dadata
>  SUP-7657: правки индекса в dadata

- local/php_interface/init.php
- test_order.php
создание обработчика привязки курьера
>  SUP-7813: edit auto courier

- js/main.js
- local/templates/.default/components/bitrix/catalog/catalog_comments/bitrix/catalog.element/.default/template.php
- local/templates/.default/components/bitrix/catalog/catalog_reviews/bitrix/catalog.element/.default/template.php
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/result_modifier.php
- local/templates/.default/components/bitrix/catalog/catalog_template/bitrix/catalog.element/.default/template.php
доработка скриптов и шаблона карточки товара для передачи в урл адресов вкладок "отзывы" и "рецензии"
> SUP-8057: fix template script
